# Set update schedule for GitHub Actions
version: 2
updates:
  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for yarn
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
