name: Build Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetupNode
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
