name: 'Deploy AD Knowledge portal'

on:
  push:
    branches:
      - main
    paths:
      - 'apps/portals/adknowledgeportal/**'
      - 'apps/synapse-portal-framework/**'
      - 'packages/synapse-react-client/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build-and-deploy-portal.yml
    with:
      portal-name: adknowledgeportal
      branch-or-tag: main
