name: 'Deploy Standards portal'

on:
  push:
    branches:
      - main
    paths:
      - '.github/**' # temporarily track GH Actions changes to test
      - 'apps/portals/standards/**'
      - 'apps/synapse-portal-framework/**'
      - 'packages/synapse-react-client/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build-and-deploy-portal.yml
    with:
      portal-name: standards
      branch-or-tag: main
