name: 'NPM Publish and GitHub tag'
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/pnpm-setup-action
      - run: pnpm -r publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  tag:
    strategy:
      matrix:
        publishablePackage: [synapse-react-client, markdown-it-synapse]
    runs-on: ubuntu-latest
    steps:
      # Now check if the package version changed
      - id: package-version-check
        uses: EndBug/version-check@v2
        with:
          file-name: ./packages/${{ matrix.publishablePackage }}/package.json
      # If the package version changed, create the tag using the output of the previous step.
      - name: Create tag
        uses: actions/github-script@v6
        if: steps.package-version-check.outputs.changed == 'true'
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ matrix.publishablePackage }}/v${{ steps.package-version-check.outputs.version }}",
              sha: context.sha
            })
