name: 'Publish Storybook'

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/pnpm-setup-action
      - name: Build docs
        run: pnpm nx run synapse-react-client:build:docs
      - name: Deploy docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: packages/synapse-react-client/storybook-static
